---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: service-2048
spec:
  ports:
    - port: 8800
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-2048