
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.port }}