
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ .Values.name }}