---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: deployment-2048
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: prod
  name: service-2048
spec:
  ports:
    - port: 8900
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-2048
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prod
  name: demo
data:
  # property-like keys; each key maps to a simple value
  ConnectionStrings__EventStore: "eventstore-connection-string-here"
  ConnectionStrings__Projection: "projection-connection-string-here"
  AWS__Profile: "Support"